### ISSUE TITLE
unable to see Custom Plugins on Plugins page

### ISSUE THREAD

**Issue by elhackeado** [Kong/kong-manager#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 3.6

### Current Behavior

Earlier version, kong 3.5 was showing Custom Built plugins on Kong Manager UI Plugins page. But newly shipped kong manager with kong 3.6 seems to have some kind of bug, unable to see any custom built plugin on UI.

### Steps To Reproduce

1. Build any custom plugin with kong 3.6 as base container image.
2. Check kong manager plugins page, it should show the custom plugin on the page, but doesn't.

**Comment by nekolab** [comment]
Hi @elhackeado 
Thanks for the feedback! We have reproduced this issue and are investigating it now

**Comment by elhackeado** [comment]
@nekolab how soon can this be fixed ?

**Comment by Leopoldthecoder** [comment]
Hi @elhackeado, the fix is in #185 but we don't have a release date yet. Meanwhile, as a workaround, you can manually change the URL in your browser to create a custom plugin. For example, `/plugins/plugin-foo/create?redirect=/plugins`, assuming the name of your custom plugin is `plugin-foo`.

Once #185 is merged, you could also build and serve the Kong Manager UI from the source code to include the fix.
