### ISSUE TITLE
packages Not Found

### ISSUE THREAD

**Issue by Lorryrui** [Kong/kong-manager#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

latest

### Steps To Reproduce

error An unexpected error occurred: "https://registry.yarnpkg.com/@kong-ui/entities-shared/-/entities-shared-0.44.2.tgz: Request failed \"404 Not Found\"".

node : v18.16.1
yarn: 1.22.19

**Comment by Leopoldthecoder** [comment]
Hi, please refer to the [Contributing](https://github.com/Kong/kong-manager#contributing) section where we mention that right now this repo is not yet ready to be run locally by the community. We are migrating our private dependencies to public packages, and when we're done (hopefully in August), you can install these dependencies.

Plus, if you only seek to **use** Kong Manager instead of contributing to it or building it on your own, you can wait for our Kong Gateway 3.4 release, which provides an out-of-box experience of this GUI.

**Comment by Leopoldthecoder** [comment]
Hi @Lorryrui, if you are still interested, we have migrated all private dependencies to public packages and now this repo is ready for community users to run locally. Kong Gateway 3.4 is also released, so you can experience Kong Manager with it out of the box.
